### ISSUE TITLE
EAMENA v4 general issue thread

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#16]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
# insert reprex here
```

**Comment by zoometh** [comment]
Online navigation between menus (ex: Map Layers Properties, Users) is too long. Chrome Inspector shows:

```
caught TypeError: Cannot read properties of null (reading 'en')
    at search.js:2:1289451
    at Array.forEach (<anonymous>)
    at viewModel.<anonymous> (search.js:2:1289229)
    at c (search.js:2:4064952)
    at Object.fireWith [as resolveWith] (search.js:2:4065779)
    at l (search.js:2:4121272)
    at XMLHttpRequest.<anonymous> (search.js:2:4123917)
```

Possibly a cache error (`en/` used to appear in EAv3 but doesn't exist anymore)

**Comment by zoometh** [comment]
The Overlays aren't accessible by all previous users

![image](https://github.com/eamena-project/eamena-arches-dev/assets/67924910/fe6212c6-ab53-4b17-b447-091d9422c7b3)

Much of user names (under **Users** section) have been removed. It doesn't see that I can add them editing the node (Heritage Place node) as suggested in the information message

**Comment by zoometh** [comment]
Impossible to change the

**Comment by zoometh** [comment]
There are missing buttons here:

![image](https://github.com/eamena-project/eamena-arches-dev/assets/67924910/b6c34edd-3f5b-4797-b499-9218190d5421)
